spring.application.name=communal_folder_gestion

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?currentSchema=communal
spring.datasource.username=postgres
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver
